Resources:
  MyFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: main-cloudformation
        S3Key: cloudwatch_to_slack.zip
      Description: Guardian-to-Slack
      FunctionName: cloudwatch_to_slack
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: !GetAtt CloudwatchToSlackRole.Arn
      Runtime: python3.7
      Timeout: 30


  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: guardian

  MySNSTopicLambdaSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      TopicArn: !Ref MySNSTopic
      Endpoint: !GetAtt MyFunction.Arn
    DependsOn:
      - MySNSTopicLambdaPermission

  MySNSTopicLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref MyFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref MySNSTopic
    DependsOn:
      - MySNSTopic


  CloudwatchToSlackRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - cloudformation.amazonaws.com
              - lambda.amazonaws.com
            Action:
            - sts:AssumeRole
      Policies:
      - PolicyName: src
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
                - ssm:GetParameter
                - ssm:GetParameters
                - sts:AssumeRole
                - secretsmanager:GetSecretValue
              Resource:
              - "*"
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - logs:DescribeLogStreams
              Resource:
                - arn:aws:logs:*:*:*
            - Effect: Allow
              Action: cloudwatch:DescribeAlarms
              Resource: '*'
            - Effect: Allow
              Action: cloudformation:ListExports
              Resource: '*'
            - Effect: Allow
              Action:
                - s3:ListBucket
                - s3:PutObject
                - s3:GetObject
              Resource:
                - !Sub 'arn:aws:s3:::*/'
                - !Sub 'arn:aws:s3:::*/*'
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource:
                - !Sub 'arn:aws:s3:::*/*'
            - Effect: Allow
              Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:SendMessage
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - lambda:DeleteFunction
              - sqs:ChangeMessageVisibility
              Resource: "*"

Parameters:
  key1:
    Type: String
    Default: "default_value1"
    